Add missing User import in module_extensions router
Fix NameError by adding back the User import that is needed for type hints in function signatures.

Error fixed:
  NameError: name 'User' is not defined